export interface WordEntry {
  en: string;
  ru: string;
  synonyms: string[];
}

export const WORD_LIST: WordEntry[] = [
  { en: "aircraft carrier", ru: "авианосец", synonyms: ["авианосец"] },
  { en: "airplane", ru: "самолёт", synonyms: ["самолёт", "самолет", "самолётик"] },
  { en: "alarm clock", ru: "будильник", synonyms: ["будильник"] },
  { en: "ambulance", ru: "скорая помощь", synonyms: ["скорая", "скорая помощь"] },
  { en: "angel", ru: "ангел", synonyms: ["ангел"] },
  { en: "ant", ru: "муравей", synonyms: ["муравей", "муравьи"] },
  { en: "anvil", ru: "наковальня", synonyms: ["наковальня"] },
  { en: "apple", ru: "яблоко", synonyms: ["яблоко", "яблочко"] },
  { en: "asparagus", ru: "спаржа", synonyms: ["спаржа"] },
  { en: "axe", ru: "топор", synonyms: ["топор", "топорик"] },
  { en: "backpack", ru: "рюкзак", synonyms: ["рюкзак", "рюкзачок"] },
  { en: "banana", ru: "банан", synonyms: ["банан", "бананчик"] },
  { en: "bandage", ru: "бинт", synonyms: ["бинт", "повязка", "пластырь"] },
  { en: "barn", ru: "амбар", synonyms: ["амбар", "сарай", "ферма"] },
  { en: "baseball", ru: "бейсбольный мяч", synonyms: ["бейсбол", "мяч", "бейсбольный мяч"] },
  { en: "baseball bat", ru: "бейсбольная бита", synonyms: ["бита", "бейсбольная бита"] },
  { en: "basket", ru: "корзина", synonyms: ["корзина", "корзинка"] },
  { en: "basketball", ru: "баскетбол", synonyms: ["баскетбол", "баскетбольный мяч"] },
  { en: "bat", ru: "летучая мышь", synonyms: ["летучая мышь", "мышь", "нетопырь"] },
  { en: "bathtub", ru: "ванна", synonyms: ["ванна", "ванночка", "ванная"] },
  { en: "beach", ru: "пляж", synonyms: ["пляж", "берег"] },
  { en: "bear", ru: "медведь", synonyms: ["медведь", "медведик", "мишка"] },
  { en: "beard", ru: "борода", synonyms: ["борода", "бородка"] },
  { en: "bed", ru: "кровать", synonyms: ["кровать", "кроватка", "постель"] },
  { en: "bee", ru: "пчела", synonyms: ["пчела", "пчёлка", "пчелка"] },
  { en: "belt", ru: "ремень", synonyms: ["ремень", "пояс", "ремешок"] },
  { en: "bench", ru: "скамейка", synonyms: ["скамейка", "скамья", "лавочка"] },
  { en: "bicycle", ru: "велосипед", synonyms: ["велосипед", "велик"] },
  { en: "binoculars", ru: "бинокль", synonyms: ["бинокль"] },
  { en: "bird", ru: "птица", synonyms: ["птица", "птичка"] },
  { en: "birthday cake", ru: "именинный торт", synonyms: ["торт", "тортик", "именинный торт", "праздничный торт"] },
  { en: "blackberry", ru: "ежевика", synonyms: ["ежевика"] },
  { en: "blueberry", ru: "черника", synonyms: ["черника", "голубика"] },
  { en: "book", ru: "книга", synonyms: ["книга", "книжка"] },
  { en: "boomerang", ru: "бумеранг", synonyms: ["бумеранг"] },
  { en: "bowtie", ru: "галстук-бабочка", synonyms: ["галстук-бабочка", "бабочка"] },
  { en: "bracelet", ru: "браслет", synonyms: ["браслет"] },
  { en: "brain", ru: "мозг", synonyms: ["мозг", "мозги"] },
  { en: "bread", ru: "хлеб", synonyms: ["хлеб", "булка", "батон"] },
  { en: "bridge", ru: "мост", synonyms: ["мост", "мостик"] },
  { en: "broccoli", ru: "брокколи", synonyms: ["брокколи"] },
  { en: "broom", ru: "метла", synonyms: ["метла", "метёлка", "метелка"] },
  { en: "bucket", ru: "ведро", synonyms: ["ведро", "ведерко"] },
  { en: "bulldozer", ru: "бульдозер", synonyms: ["бульдозер"] },
  { en: "bus", ru: "автобус", synonyms: ["автобус", "маршрутка"] },
  { en: "bush", ru: "куст", synonyms: ["куст", "кустик", "кустарник"] },
  { en: "butterfly", ru: "бабочка", synonyms: ["бабочка", "мотылёк", "мотылек"] },
  { en: "cactus", ru: "кактус", synonyms: ["кактус", "кактусик"] },
  { en: "cake", ru: "торт", synonyms: ["торт", "пирог", "пирожное", "тортик"] },
  { en: "calculator", ru: "калькулятор", synonyms: ["калькулятор"] },
  { en: "calendar", ru: "календарь", synonyms: ["календарь"] },
  { en: "camel", ru: "верблюд", synonyms: ["верблюд"] },
  { en: "camera", ru: "фотоаппарат", synonyms: ["фотоаппарат", "камера", "фотик"] },
  { en: "campfire", ru: "костёр", synonyms: ["костёр", "костер"] },
  { en: "candle", ru: "свеча", synonyms: ["свеча", "свечка"] },
  { en: "cannon", ru: "пушка", synonyms: ["пушка", "орудие"] },
  { en: "canoe", ru: "каноэ", synonyms: ["каноэ", "лодка"] },
  { en: "car", ru: "машина", synonyms: ["машина", "автомобиль", "авто", "тачка"] },
  { en: "carrot", ru: "морковь", synonyms: ["морковь", "морковка"] },
  { en: "castle", ru: "замок", synonyms: ["замок", "крепость"] },
  { en: "cat", ru: "кот", synonyms: ["кот", "кошка", "котёнок", "котик"] },
  { en: "ceiling fan", ru: "потолочный вентилятор", synonyms: ["вентилятор", "потолочный вентилятор"] },
  { en: "cello", ru: "виолончель", synonyms: ["виолончель"] },
  { en: "cell phone", ru: "мобильный телефон", synonyms: ["телефон", "мобильник", "смартфон", "мобильный"] },
  { en: "chair", ru: "стул", synonyms: ["стул", "стульчик", "кресло"] },
  { en: "chandelier", ru: "люстра", synonyms: ["люстра"] },
  { en: "church", ru: "церковь", synonyms: ["церковь", "храм", "собор"] },
  { en: "circle", ru: "круг", synonyms: ["круг", "кружок", "окружность"] },
  { en: "clarinet", ru: "кларнет", synonyms: ["кларнет"] },
  { en: "clock", ru: "часы", synonyms: ["часы", "часики"] },
  { en: "cloud", ru: "облако", synonyms: ["облако", "облачко", "туча"] },
  { en: "coffee cup", ru: "кофе", synonyms: ["кофе", "чашка кофе", "кофейная чашка"] },
  { en: "compass", ru: "компас", synonyms: ["компас"] },
  { en: "computer", ru: "компьютер", synonyms: ["компьютер", "ноутбук", "ПК"] },
  { en: "cookie", ru: "печенье", synonyms: ["печенье", "печенька"] },
  { en: "couch", ru: "диван", synonyms: ["диван", "диванчик", "кушетка"] },
  { en: "cow", ru: "корова", synonyms: ["корова", "коровка", "бурёнка"] },
  { en: "crab", ru: "краб", synonyms: ["краб", "крабик"] },
  { en: "crayon", ru: "восковой мелок", synonyms: ["мелок", "восковой мелок"] },
  { en: "crocodile", ru: "крокодил", synonyms: ["крокодил", "аллигатор"] },
  { en: "crown", ru: "корона", synonyms: ["корона", "венец"] },
  { en: "cruise ship", ru: "круизный лайнер", synonyms: ["лайнер", "круизный лайнер", "корабль"] },
  { en: "cup", ru: "кружка", synonyms: ["кружка", "чашка", "стакан"] },
  { en: "diamond", ru: "бриллиант", synonyms: ["бриллиант", "алмаз", "ромб"] },
  { en: "dishwasher", ru: "посудомоечная машина", synonyms: ["посудомойка", "посудомоечная машина"] },
  { en: "dog", ru: "собака", synonyms: ["собака", "пёс", "щенок", "собачка"] },
  { en: "dolphin", ru: "дельфин", synonyms: ["дельфин", "дельфинчик"] },
  { en: "donut", ru: "пончик", synonyms: ["пончик", "пончики", "донат"] },
  { en: "door", ru: "дверь", synonyms: ["дверь", "дверка", "дверца"] },
  { en: "dragon", ru: "дракон", synonyms: ["дракон"] },
  { en: "dresser", ru: "комод", synonyms: ["комод", "тумба"] },
  { en: "drill", ru: "дрель", synonyms: ["дрель", "бур"] },
  { en: "drums", ru: "барабаны", synonyms: ["барабаны", "барабан", "ударные"] },
  { en: "duck", ru: "утка", synonyms: ["утка", "уточка", "утёнок"] },
  { en: "dumbbell", ru: "гантели", synonyms: ["гантели", "гантеля", "гантель"] },
  { en: "ear", ru: "ухо", synonyms: ["ухо", "уши"] },
  { en: "elephant", ru: "слон", synonyms: ["слон", "слоник", "слониха"] },
  { en: "envelope", ru: "конверт", synonyms: ["конверт", "конвертик"] },
  { en: "eraser", ru: "ластик", synonyms: ["ластик", "резинка"] },
  { en: "eye", ru: "глаз", synonyms: ["глаз", "глазик", "глаза"] },
  { en: "eyeglasses", ru: "очки", synonyms: ["очки", "очки для зрения"] },
  { en: "face", ru: "лицо", synonyms: ["лицо", "мордочка", "голова"] },
  { en: "fan", ru: "веер", synonyms: ["веер", "вентилятор"] },
  { en: "feather", ru: "перо", synonyms: ["перо", "перышко"] },
  { en: "fence", ru: "забор", synonyms: ["забор", "заборчик", "изгородь"] },
  { en: "finger", ru: "палец", synonyms: ["палец", "пальчик"] },
  { en: "fire hydrant", ru: "пожарный гидрант", synonyms: ["гидрант", "пожарный гидрант"] },
  { en: "fireplace", ru: "камин", synonyms: ["камин", "печь"] },
  { en: "firetruck", ru: "пожарная машина", synonyms: ["пожарная машина", "пожарка"] },
  { en: "fish", ru: "рыба", synonyms: ["рыба", "рыбка"] },
  { en: "flamingo", ru: "фламинго", synonyms: ["фламинго"] },
  { en: "flashlight", ru: "фонарик", synonyms: ["фонарик", "фонарь"] },
  { en: "flip flops", ru: "шлёпанцы", synonyms: ["шлёпанцы", "шлепки", "вьетнамки"] },
  { en: "floor lamp", ru: "торшер", synonyms: ["торшер", "напольная лампа"] },
  { en: "flower", ru: "цветок", synonyms: ["цветок", "цветочек", "цветы"] },
  { en: "flying saucer", ru: "летающая тарелка", synonyms: ["летающая тарелка", "нло", "НЛО"] },
  { en: "foot", ru: "ступня", synonyms: ["ступня", "нога", "стопа"] },
  { en: "fork", ru: "вилка", synonyms: ["вилка", "вилочка"] },
  { en: "frog", ru: "лягушка", synonyms: ["лягушка", "лягушонок", "жаба"] },
  { en: "frying pan", ru: "сковорода", synonyms: ["сковорода", "сковородка"] },
  { en: "garden", ru: "сад", synonyms: ["сад", "огород", "садик"] },
  { en: "garden hose", ru: "садовый шланг", synonyms: ["шланг", "садовый шланг"] },
  { en: "giraffe", ru: "жираф", synonyms: ["жираф"] },
  { en: "golf club", ru: "клюшка для гольфа", synonyms: ["клюшка", "клюшка для гольфа"] },
  { en: "grapes", ru: "виноград", synonyms: ["виноград", "виноградина"] },
  { en: "grass", ru: "трава", synonyms: ["трава", "газон"] },
  { en: "guitar", ru: "гитара", synonyms: ["гитара", "гитарка"] },
  { en: "hamburger", ru: "гамбургер", synonyms: ["гамбургер", "бургер"] },
  { en: "hammer", ru: "молоток", synonyms: ["молоток", "молоточек"] },
  { en: "hand", ru: "рука", synonyms: ["рука", "ладонь", "кисть"] },
  { en: "harp", ru: "арфа", synonyms: ["арфа"] },
  { en: "hat", ru: "шляпа", synonyms: ["шляпа", "шляпка", "шапка"] },
  { en: "headphones", ru: "наушники", synonyms: ["наушники", "наушник"] },
  { en: "hedgehog", ru: "ёжик", synonyms: ["ёжик", "ежик", "ёж"] },
  { en: "helicopter", ru: "вертолёт", synonyms: ["вертолёт", "вертолет", "вертушка"] },
  { en: "helmet", ru: "шлем", synonyms: ["шлем", "каска"] },
  { en: "hockey puck", ru: "хоккейная шайба", synonyms: ["шайба", "хоккейная шайба"] },
  { en: "hockey stick", ru: "хоккейная клюшка", synonyms: ["клюшка", "хоккейная клюшка"] },
  { en: "horse", ru: "лошадь", synonyms: ["лошадь", "лошадка", "конь"] },
  { en: "hospital", ru: "больница", synonyms: ["больница", "госпиталь"] },
  { en: "hot air balloon", ru: "воздушный шар", synonyms: ["воздушный шар", "аэростат"] },
  { en: "hot dog", ru: "хот-дог", synonyms: ["хот-дог", "сосиска"] },
  { en: "hot tub", ru: "джакузи", synonyms: ["джакузи", "ванна"] },
  { en: "hourglass", ru: "песочные часы", synonyms: ["песочные часы"] },
  { en: "house", ru: "дом", synonyms: ["дом", "домик", "здание"] },
  { en: "house plant", ru: "комнатное растение", synonyms: ["комнатное растение", "цветок в горшке", "горшок"] },
  { en: "ice cream", ru: "мороженое", synonyms: ["мороженое", "мороженка"] },
  { en: "jacket", ru: "куртка", synonyms: ["куртка", "пиджак", "жакет"] },
  { en: "jail", ru: "тюрьма", synonyms: ["тюрьма", "решётка", "темница"] },
  { en: "kangaroo", ru: "кенгуру", synonyms: ["кенгуру"] },
  { en: "key", ru: "ключ", synonyms: ["ключ", "ключик"] },
  { en: "keyboard", ru: "клавиатура", synonyms: ["клавиатура"] },
  { en: "knife", ru: "нож", synonyms: ["нож", "ножик"] },
  { en: "ladder", ru: "стремянка", synonyms: ["лестница", "стремянка", "лесенка"] },
  { en: "lantern", ru: "фонарь", synonyms: ["фонарь", "фонарик", "светильник"] },
  { en: "laptop", ru: "ноутбук", synonyms: ["ноутбук", "лэптоп"] },
  { en: "leaf", ru: "листок", synonyms: ["листок", "лист", "листочек"] },
  { en: "leg", ru: "нога", synonyms: ["нога", "ноги"] },
  { en: "light bulb", ru: "лампочка", synonyms: ["лампочка", "лампа"] },
  { en: "lighter", ru: "зажигалка", synonyms: ["зажигалка"] },
  { en: "lighthouse", ru: "маяк", synonyms: ["маяк"] },
  { en: "lightning", ru: "молния", synonyms: ["молния", "гроза"] },
  { en: "lion", ru: "лев", synonyms: ["лев", "львёнок", "львенок"] },
  { en: "lipstick", ru: "помада", synonyms: ["помада", "губная помада"] },
  { en: "lobster", ru: "омар", synonyms: ["омар", "лобстер"] },
  { en: "lollipop", ru: "леденец", synonyms: ["леденец", "чупа-чупс"] },
  { en: "mailbox", ru: "почтовый ящик", synonyms: ["почтовый ящик", "ящик"] },
  { en: "map", ru: "карта", synonyms: ["карта", "карта мира"] },
  { en: "marker", ru: "маркер", synonyms: ["маркер", "фломастер"] },
  { en: "matches", ru: "спички", synonyms: ["спички", "спичка"] },
  { en: "megaphone", ru: "мегафон", synonyms: ["мегафон", "рупор"] },
  { en: "mermaid", ru: "русалка", synonyms: ["русалка"] },
  { en: "microphone", ru: "микрофон", synonyms: ["микрофон", "микрофончик"] },
  { en: "microwave", ru: "микроволновка", synonyms: ["микроволновка", "микроволновая печь"] },
  { en: "monkey", ru: "обезьяна", synonyms: ["обезьяна", "обезьянка", "мартышка"] },
  { en: "moon", ru: "луна", synonyms: ["луна", "месяц"] },
  { en: "mosquito", ru: "комар", synonyms: ["комар", "комарик"] },
  { en: "motorbike", ru: "мотоцикл", synonyms: ["мотоцикл", "мотик"] },
  { en: "mountain", ru: "гора", synonyms: ["гора", "горы", "горка"] },
  { en: "mouse", ru: "мышь", synonyms: ["мышь", "мышка", "мышонок"] },
  { en: "moustache", ru: "усы", synonyms: ["усы", "ус", "усики"] },
  { en: "mouth", ru: "рот", synonyms: ["рот", "губы"] },
  { en: "mug", ru: "кружка", synonyms: ["кружка", "кружечка"] },
  { en: "mushroom", ru: "гриб", synonyms: ["гриб", "грибок", "грибочек"] },
  { en: "nail", ru: "гвоздь", synonyms: ["гвоздь", "гвоздик"] },
  { en: "necklace", ru: "ожерелье", synonyms: ["ожерелье", "бусы", "цепочка"] },
  { en: "nose", ru: "нос", synonyms: ["нос", "носик"] },
  { en: "octopus", ru: "осьминог", synonyms: ["осьминог", "осьминожка"] },
  { en: "onion", ru: "лук", synonyms: ["лук", "луковица"] },
  { en: "oven", ru: "духовка", synonyms: ["духовка", "печь", "духовой шкаф"] },
  { en: "owl", ru: "сова", synonyms: ["сова", "совёнок", "филин"] },
  { en: "paintbrush", ru: "кисть", synonyms: ["кисть", "кисточка"] },
  { en: "paint can", ru: "банка с краской", synonyms: ["краска", "банка с краской"] },
  { en: "palm tree", ru: "пальма", synonyms: ["пальма"] },
  { en: "panda", ru: "панда", synonyms: ["панда"] },
  { en: "pants", ru: "штаны", synonyms: ["штаны", "брюки", "джинсы"] },
  { en: "paper clip", ru: "скрепка", synonyms: ["скрепка", "скрепочка"] },
  { en: "parachute", ru: "парашют", synonyms: ["парашют"] },
  { en: "parrot", ru: "попугай", synonyms: ["попугай", "попугайчик"] },
  { en: "passport", ru: "паспорт", synonyms: ["паспорт"] },
  { en: "peanut", ru: "арахис", synonyms: ["арахис", "земляной орех"] },
  { en: "pear", ru: "груша", synonyms: ["груша", "грушка"] },
  { en: "peas", ru: "горох", synonyms: ["горох", "горошек"] },
  { en: "pencil", ru: "карандаш", synonyms: ["карандаш", "карандашик"] },
  { en: "penguin", ru: "пингвин", synonyms: ["пингвин", "пингвинчик"] },
  { en: "piano", ru: "пианино", synonyms: ["пианино", "рояль"] },
  { en: "pickup truck", ru: "пикап", synonyms: ["пикап", "грузовик"] },
  { en: "picture frame", ru: "рамка", synonyms: ["рамка", "фоторамка"] },
  { en: "pig", ru: "свинья", synonyms: ["свинья", "свинка", "поросёнок", "хрюша"] },
  { en: "pillow", ru: "подушка", synonyms: ["подушка", "подушечка"] },
  { en: "pineapple", ru: "ананас", synonyms: ["ананас"] },
  { en: "pizza", ru: "пицца", synonyms: ["пицца"] },
  { en: "pliers", ru: "плоскогубцы", synonyms: ["плоскогубцы", "клещи", "щипцы"] },
  { en: "police car", ru: "полицейская машина", synonyms: ["полицейская машина", "полиция"] },
  { en: "pool", ru: "бассейн", synonyms: ["бассейн"] },
  { en: "popsicle", ru: "мороженое на палочке", synonyms: ["мороженое на палочке", "эскимо"] },
  { en: "postcard", ru: "открытка", synonyms: ["открытка", "почтовая открытка"] },
  { en: "potato", ru: "картошка", synonyms: ["картошка", "картофель"] },
  { en: "power outlet", ru: "розетка", synonyms: ["розетка"] },
  { en: "purse", ru: "сумочка", synonyms: ["сумочка", "сумка", "кошелёк", "кошелек"] },
  { en: "rabbit", ru: "кролик", synonyms: ["кролик", "заяц", "зайчик", "зайка"] },
  { en: "raccoon", ru: "енот", synonyms: ["енот", "енотик"] },
  { en: "radio", ru: "радио", synonyms: ["радио", "радиоприёмник"] },
  { en: "rain", ru: "дождь", synonyms: ["дождь", "дождик"] },
  { en: "rainbow", ru: "радуга", synonyms: ["радуга"] },
  { en: "rake", ru: "грабли", synonyms: ["грабли", "граблик"] },
  { en: "remote control", ru: "пульт", synonyms: ["пульт", "пульт управления", "пультик"] },
  { en: "rhinoceros", ru: "носорог", synonyms: ["носорог"] },
  { en: "rifle", ru: "ружьё", synonyms: ["ружьё", "ружье", "винтовка"] },
  { en: "river", ru: "река", synonyms: ["река", "речка"] },
  { en: "roller coaster", ru: "американские горки", synonyms: ["американские горки", "горки", "аттракцион"] },
  { en: "rollerskates", ru: "ролики", synonyms: ["ролики", "роликовые коньки"] },
  { en: "sailboat", ru: "парусник", synonyms: ["парусник", "лодка", "яхта"] },
  { en: "sandwich", ru: "бутерброд", synonyms: ["бутерброд", "сэндвич"] },
  { en: "saw", ru: "пила", synonyms: ["пила", "пилка"] },
  { en: "saxophone", ru: "саксофон", synonyms: ["саксофон", "сакс"] },
  { en: "school bus", ru: "школьный автобус", synonyms: ["школьный автобус", "автобус"] },
  { en: "scissors", ru: "ножницы", synonyms: ["ножницы", "ножнички"] },
  { en: "scorpion", ru: "скорпион", synonyms: ["скорпион"] },
  { en: "screwdriver", ru: "отвёртка", synonyms: ["отвёртка", "отвертка"] },
  { en: "sea turtle", ru: "морская черепаха", synonyms: ["черепаха", "морская черепаха"] },
  { en: "see saw", ru: "качели-доска", synonyms: ["качели", "доска-качалка", "качели-доска"] },
  { en: "shark", ru: "акула", synonyms: ["акула", "акулка"] },
  { en: "sheep", ru: "овца", synonyms: ["овца", "овечка", "барашек"] },
  { en: "shoe", ru: "ботинок", synonyms: ["ботинок", "туфля", "кроссовок", "обувь"] },
  { en: "shorts", ru: "шорты", synonyms: ["шорты"] },
  { en: "shovel", ru: "лопата", synonyms: ["лопата", "лопатка"] },
  { en: "sink", ru: "раковина", synonyms: ["раковина", "умывальник"] },
  { en: "skateboard", ru: "скейтборд", synonyms: ["скейтборд", "скейт"] },
  { en: "skull", ru: "череп", synonyms: ["череп", "черепушка"] },
  { en: "skyscraper", ru: "небоскрёб", synonyms: ["небоскрёб", "небоскреб"] },
  { en: "sleeping bag", ru: "спальный мешок", synonyms: ["спальный мешок", "спальник"] },
  { en: "smiley face", ru: "смайлик", synonyms: ["смайлик", "улыбка"] },
  { en: "snail", ru: "улитка", synonyms: ["улитка"] },
  { en: "snake", ru: "змея", synonyms: ["змея", "змейка", "уж"] },
  { en: "snowflake", ru: "снежинка", synonyms: ["снежинка"] },
  { en: "snowman", ru: "снеговик", synonyms: ["снеговик"] },
  { en: "soccer ball", ru: "футбольный мяч", synonyms: ["мяч", "футбольный мяч"] },
  { en: "sock", ru: "носок", synonyms: ["носок", "носки"] },
  { en: "speedboat", ru: "катер", synonyms: ["катер", "моторная лодка"] },
  { en: "spider", ru: "паук", synonyms: ["паук", "паучок"] },
  { en: "spoon", ru: "ложка", synonyms: ["ложка", "ложечка"] },
  { en: "square", ru: "квадрат", synonyms: ["квадрат", "квадратик"] },
  { en: "squirrel", ru: "белка", synonyms: ["белка", "белочка"] },
  { en: "stairs", ru: "лестница", synonyms: ["лестница", "ступеньки"] },
  { en: "star", ru: "звезда", synonyms: ["звезда", "звёздочка", "звездочка"] },
  { en: "steak", ru: "стейк", synonyms: ["стейк", "мясо"] },
  { en: "stereo", ru: "музыкальный центр", synonyms: ["музыкальный центр", "стерео", "колонки"] },
  { en: "stethoscope", ru: "стетоскоп", synonyms: ["стетоскоп"] },
  { en: "stop sign", ru: "знак стоп", synonyms: ["знак стоп", "стоп"] },
  { en: "stove", ru: "плита", synonyms: ["плита", "плитка", "газовая плита"] },
  { en: "strawberry", ru: "клубника", synonyms: ["клубника", "клубничка"] },
  { en: "streetlight", ru: "уличный фонарь", synonyms: ["фонарь", "уличный фонарь", "фонарный столб"] },
  { en: "string bean", ru: "стручковая фасоль", synonyms: ["фасоль", "стручковая фасоль"] },
  { en: "submarine", ru: "подводная лодка", synonyms: ["подводная лодка", "субмарина"] },
  { en: "suitcase", ru: "чемодан", synonyms: ["чемодан", "чемоданчик"] },
  { en: "sun", ru: "солнце", synonyms: ["солнце", "солнышко"] },
  { en: "swan", ru: "лебедь", synonyms: ["лебедь", "лебёдушка"] },
  { en: "sweater", ru: "свитер", synonyms: ["свитер", "свитерок", "джемпер"] },
  { en: "swing set", ru: "качели", synonyms: ["качели"] },
  { en: "sword", ru: "меч", synonyms: ["меч", "сабля", "шпага"] },
  { en: "syringe", ru: "шприц", synonyms: ["шприц", "укол"] },
  { en: "table", ru: "стол", synonyms: ["стол", "столик"] },
  { en: "teapot", ru: "чайник", synonyms: ["чайник", "заварочный чайник"] },
  { en: "teddy-bear", ru: "плюшевый мишка", synonyms: ["плюшевый мишка", "мишка", "плюшевый медведь"] },
  { en: "telephone", ru: "телефон", synonyms: ["телефон", "трубка"] },
  { en: "television", ru: "телевизор", synonyms: ["телевизор", "телик", "тв", "ТВ"] },
  { en: "tennis racquet", ru: "теннисная ракетка", synonyms: ["ракетка", "теннисная ракетка"] },
  { en: "tent", ru: "палатка", synonyms: ["палатка"] },
  { en: "The Eiffel Tower", ru: "Эйфелева башня", synonyms: ["эйфелева башня", "Эйфелева башня"] },
  { en: "tiger", ru: "тигр", synonyms: ["тигр", "тигрёнок", "тигренок"] },
  { en: "toaster", ru: "тостер", synonyms: ["тостер"] },
  { en: "toilet", ru: "унитаз", synonyms: ["унитаз", "туалет"] },
  { en: "tooth", ru: "зуб", synonyms: ["зуб", "зубик", "зубы"] },
  { en: "toothbrush", ru: "зубная щётка", synonyms: ["зубная щётка", "зубная щетка", "щётка"] },
  { en: "toothpaste", ru: "зубная паста", synonyms: ["зубная паста", "паста"] },
  { en: "tornado", ru: "торнадо", synonyms: ["торнадо", "смерч", "вихрь"] },
  { en: "tractor", ru: "трактор", synonyms: ["трактор"] },
  { en: "traffic light", ru: "светофор", synonyms: ["светофор"] },
  { en: "train", ru: "поезд", synonyms: ["поезд", "паровоз", "электричка"] },
  { en: "tree", ru: "дерево", synonyms: ["дерево", "деревце", "ёлка"] },
  { en: "triangle", ru: "треугольник", synonyms: ["треугольник"] },
  { en: "trombone", ru: "тромбон", synonyms: ["тромбон"] },
  { en: "truck", ru: "грузовик", synonyms: ["грузовик", "фура"] },
  { en: "trumpet", ru: "труба", synonyms: ["труба", "горн"] },
  { en: "t-shirt", ru: "футболка", synonyms: ["футболка", "майка"] },
  { en: "umbrella", ru: "зонт", synonyms: ["зонт", "зонтик"] },
  { en: "underwear", ru: "нижнее бельё", synonyms: ["нижнее бельё", "нижнее белье", "трусы"] },
  { en: "van", ru: "микроавтобус", synonyms: ["микроавтобус", "фургон"] },
  { en: "vase", ru: "ваза", synonyms: ["ваза", "вазочка"] },
  { en: "violin", ru: "скрипка", synonyms: ["скрипка", "скрипочка"] },
  { en: "washing machine", ru: "стиральная машина", synonyms: ["стиральная машина", "стиралка"] },
  { en: "watermelon", ru: "арбуз", synonyms: ["арбуз", "арбузик"] },
  { en: "waterslide", ru: "водная горка", synonyms: ["водная горка", "горка"] },
  { en: "whale", ru: "кит", synonyms: ["кит"] },
  { en: "wheel", ru: "колесо", synonyms: ["колесо", "колёсико"] },
  { en: "windmill", ru: "ветряная мельница", synonyms: ["ветряная мельница", "мельница", "ветряк"] },
  { en: "wine bottle", ru: "бутылка вина", synonyms: ["бутылка вина", "бутылка"] },
  { en: "wine glass", ru: "бокал", synonyms: ["бокал", "бокал для вина", "фужер"] },
  { en: "wristwatch", ru: "наручные часы", synonyms: ["наручные часы", "часы"] },
  { en: "zebra", ru: "зебра", synonyms: ["зебра"] },
];

export function getRandomWord(): WordEntry {
  return WORD_LIST[Math.floor(Math.random() * WORD_LIST.length)];
}

export function getWordByEn(en: string): WordEntry | undefined {
  return WORD_LIST.find((w) => w.en === en);
}
